# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Issues with these labels will never be considered stale
exemptLabels:
- Bug
- Quality
- Feedback
- Libraries
- Feature request
# Label to use when marking an issue as stale
staleLabel: First warning
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This is a message to remind you that your request was pending for 8 days. 
  
  Our agent would like to hear from you regarding your previous request to see if the issue has been resolved. In the meantime, the issue will be closed, but feel free to reopen it in case you need further assitance.

  Kind regards,
  Electronic Cats Support Team
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true
# Limit to only `issues` or `pulls`
only: issues
